export const styles = {
  container: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '20px',
  },
  navbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 40px',
    background: 'rgba(26, 26, 46, 0.95)',
    backdropFilter: 'blur(10px)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    borderBottom: '1px solid rgba(233, 69, 96, 0.3)',
  },
  logo: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#e94560',
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  navLinks: {
    display: 'flex',
    gap: '30px',
  },
  navLink: {
    color: '#fff',
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: '500',
    transition: 'color 0.3s',
    padding: '8px 16px',
    borderRadius: '8px',
  },
  heroSection: {
    textAlign: 'center',
    padding: '60px 20px',
    background: 'linear-gradient(135deg, rgba(233, 69, 96, 0.1) 0%, rgba(22, 33, 62, 0.5) 100%)',
    borderRadius: '20px',
    marginBottom: '40px',
  },
  heroTitle: {
    fontSize: '48px',
    fontWeight: '700',
    marginBottom: '15px',
    background: 'linear-gradient(90deg, #e94560, #ff6b6b)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroSubtitle: {
    fontSize: '18px',
    color: '#a0a0a0',
    maxWidth: '600px',
    margin: '0 auto',
  },
  filterSection: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '15px',
    marginBottom: '30px',
    padding: '20px',
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '15px',
  },
  searchInput: {
    flex: '1',
    minWidth: '250px',
    padding: '12px 20px',
    borderRadius: '10px',
    border: '2px solid rgba(233, 69, 96, 0.3)',
    background: 'rgba(26, 26, 46, 0.8)',
    color: '#fff',
    fontSize: '16px',
    outline: 'none',
    transition: 'border-color 0.3s',
  },
  select: {
    padding: '12px 20px',
    borderRadius: '10px',
    border: '2px solid rgba(233, 69, 96, 0.3)',
    background: 'rgba(26, 26, 46, 0.8)',
    color: '#fff',
    fontSize: '16px',
    outline: 'none',
    cursor: 'pointer',
    minWidth: '150px',
  },
  moviesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '25px',
    padding: '20px 0',
  },
  movieCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '15px',
    overflow: 'hidden',
    transition: 'transform 0.3s, box-shadow 0.3s',
    cursor: 'pointer',
    border: '1px solid rgba(233, 69, 96, 0.2)',
  },
  movieImage: {
    width: '100%',
    height: '350px',
    objectFit: 'cover',
    background: 'linear-gradient(135deg, #2a2a4a 0%, #1a1a2e 100%)',
  },
  movieInfo: {
    padding: '20px',
  },
  movieTitle: {
    fontSize: '18px',
    fontWeight: '600',
    marginBottom: '8px',
    color: '#fff',
  },
  movieMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  genreBadge: {
    background: 'linear-gradient(90deg, #e94560, #ff6b6b)',
    padding: '5px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: '500',
  },
  rating: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    color: '#ffd700',
    fontWeight: '600',
  },
  detailPage: {
    padding: '40px 20px',
  },
  detailContainer: {
    display: 'grid',
    gridTemplateColumns: '400px 1fr',
    gap: '40px',
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '20px',
    overflow: 'hidden',
  },
  detailImage: {
    width: '100%',
    height: '100%',
    minHeight: '500px',
    objectFit: 'cover',
  },
  detailInfo: {
    padding: '40px 40px 40px 0',
  },
  detailTitle: {
    fontSize: '36px',
    fontWeight: '700',
    marginBottom: '20px',
  },
  detailMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '15px',
    marginBottom: '25px',
  },
  metaItem: {
    background: 'rgba(233, 69, 96, 0.2)',
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '14px',
  },
  description: {
    fontSize: '16px',
    lineHeight: '1.8',
    color: '#c0c0c0',
    marginBottom: '25px',
  },
  infoRow: {
    display: 'flex',
    gap: '10px',
    marginBottom: '15px',
    fontSize: '15px',
  },
  infoLabel: {
    color: '#a0a0a0',
    minWidth: '100px',
  },
  infoValue: {
    color: '#fff',
    fontWeight: '500',
  },
  adminContainer: {
    padding: '40px 20px',
  },
  adminHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
  },
  adminTitle: {
    fontSize: '32px',
    fontWeight: '700',
  },
  addButton: {
    background: 'linear-gradient(90deg, #e94560, #ff6b6b)',
    color: '#fff',
    border: 'none',
    padding: '12px 25px',
    borderRadius: '10px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'transform 0.3s',
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.8)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalContent: {
    background: '#1a1a2e',
    borderRadius: '20px',
    padding: '30px',
    width: '100%',
    maxWidth: '600px',
    maxHeight: '90vh',
    overflowY: 'auto',
    border: '1px solid rgba(233, 69, 96, 0.3)',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: '600',
    marginBottom: '25px',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#a0a0a0',
  },
  input: {
    padding: '12px 16px',
    borderRadius: '10px',
    border: '2px solid rgba(233, 69, 96, 0.3)',
    background: 'rgba(26, 26, 46, 0.8)',
    color: '#fff',
    fontSize: '16px',
    outline: 'none',
  },
  textarea: {
    padding: '12px 16px',
    borderRadius: '10px',
    border: '2px solid rgba(233, 69, 96, 0.3)',
    background: 'rgba(26, 26, 46, 0.8)',
    color: '#fff',
    fontSize: '16px',
    outline: 'none',
    minHeight: '120px',
    resize: 'vertical',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '15px',
  },
  buttonGroup: {
    display: 'flex',
    gap: '15px',
    marginTop: '10px',
  },
  submitButton: {
    flex: 1,
    background: 'linear-gradient(90deg, #e94560, #ff6b6b)',
    color: '#fff',
    border: 'none',
    padding: '14px',
    borderRadius: '10px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  cancelButton: {
    flex: 1,
    background: 'transparent',
    color: '#fff',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    padding: '14px',
    borderRadius: '10px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  adminTable: {
    width: '100%',
    borderCollapse: 'collapse',
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '15px',
    overflow: 'hidden',
  },
  tableHeader: {
    background: 'rgba(233, 69, 96, 0.2)',
  },
  th: {
    padding: '15px 20px',
    textAlign: 'left',
    fontWeight: '600',
    fontSize: '14px',
    color: '#e94560',
  },
  td: {
    padding: '15px 20px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    fontSize: '14px',
  },
  tableImage: {
    width: '60px',
    height: '80px',
    objectFit: 'cover',
    borderRadius: '8px',
  },
  actionButton: {
    padding: '8px 15px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    marginRight: '8px',
  },
  editButton: {
    background: '#3498db',
    color: '#fff',
  },
  deleteButton: {
    background: '#e74c3c',
    color: '#fff',
  },
  fileInput: {
    padding: '12px',
    borderRadius: '10px',
    border: '2px dashed rgba(233, 69, 96, 0.5)',
    background: 'rgba(26, 26, 46, 0.8)',
    color: '#fff',
    cursor: 'pointer',
  },
  previewImage: {
    width: '100%',
    maxHeight: '200px',
    objectFit: 'cover',
    borderRadius: '10px',
    marginTop: '10px',
  },
  backButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    color: '#e94560',
    textDecoration: 'none',
    fontSize: '16px',
    marginBottom: '20px',
    fontWeight: '500',
  },
  recommendSection: {
    marginTop: '50px',
    paddingTop: '30px',
    borderTop: '1px solid rgba(255, 255, 255, 0.1)',
  },
  recommendTitle: {
    fontSize: '24px',
    fontWeight: '600',
    marginBottom: '20px',
  },
  emptyState: {
    textAlign: 'center',
    padding: '80px 20px',
    color: '#a0a0a0',
  },
  emptyIcon: {
    fontSize: '64px',
    marginBottom: '20px',
  },
};