export const styles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '20px',
  },
  navbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '15px 30px',
    background: '#871700ff',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
  },
  navBrand: {
    display: 'flex',
    alignItems: 'center',
  },
  navLogo: {
    fontSize: '24px',
    fontWeight: '800',
    color: '#fff',
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  navLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  navLink: {
    color: '#fff',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '600',
    padding: '6px 12px',
    border: '1px solid transparent',
    transition: 'all 0.2s ease',
  },
  navLinkHover: {
    background: 'rgba(255, 255, 255, 0.1)',
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    padding: '5px 15px',
    border: '1px solid rgba(255, 255, 255, 0.3)',
  },
  welcomeText: {
    color: '#fff',
    fontSize: '13px',
    fontWeight: '600',
  },
  logoutButton: {
    background: 'transparent',
    color: '#fff',
    border: 'none',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    padding: '5px 10px',
    textDecoration: 'underline',
  },
  registerBtn: {
    background: '#fb320b',
    color: '#fff',
    textDecoration: 'none',
    padding: '8px 20px',
    fontSize: '14px',
    fontWeight: '700',
    transition: 'all 0.2s',
    border: '1px solid #fff',
  },
  heroSection: {
    textAlign: 'center',
    padding: '60px 20px',
    background: '#fff',
    borderBottom: '1px solid #f0f7ff',
    marginBottom: '30px',
  },
  heroTitle: {
    fontSize: '42px',
    fontWeight: '800',
    marginBottom: '10px',
    color: '#fb320b',
    textTransform: 'uppercase',
    letterSpacing: '-1px',
  },
  heroSubtitle: {
    fontSize: '16px',
    color: '#666',
    maxWidth: '600px',
    margin: '0 auto',
  },
  filterSection: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    marginBottom: '30px',
    padding: '20px',
    background: '#fff',
    border: '2px solid #000',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
  },
  searchInput: {
    flex: '1',
    minWidth: '250px',
    padding: '10px 15px',
    border: '2px solid #000',
    background: '#fff',
    color: '#000',
    fontSize: '14px',
    outline: 'none',
    transition: 'all 0.2s',
  },
  select: {
    padding: '10px 15px',
    border: '2px solid #000',
    background: '#fff',
    color: '#000',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    minWidth: '150px',
    transition: 'all 0.2s',
  },
  moviesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '30px',
    padding: '20px 0',
  },
  movieCard: {
    background: '#fff',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'pointer',
    border: '2px solid #000',
    padding: '10px',
    color: '#000',
  },
  movieCardHover: {
    borderColor: '#000',
    transform: 'translateY(-4px)',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.1)',
  },
  movieImage: {
    width: '100%',
    height: '350px',
    objectFit: 'cover',
    background: '#f5f5f5',
    border: '1px solid #000',
  },
  movieInfo: {
    padding: '15px 5px',
  },
  movieTitle: {
    fontSize: '16px',
    fontWeight: '700',
    marginBottom: '8px',
    color: '#000',
    textTransform: 'uppercase',
  },
  movieMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  genreBadge: {
    background: '#000',
    padding: '4px 8px',
    fontSize: '11px',
    fontWeight: '700',
    color: '#fff',
    textTransform: 'uppercase',
  },
  rating: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    color: '#000',
    fontWeight: '700',
    fontSize: '14px',
  },
  detailPage: {
    padding: '40px 20px',
  },
  detailContainer: {
    display: 'grid',
    gridTemplateColumns: '350px 1fr',
    gap: '40px',
    background: '#fff',
    padding: '20px',
    border: '3px solid #000',
  },
  detailImage: {
    width: '100%',
    height: 'auto',
    objectFit: 'cover',
    border: '2px solid #000',
  },
  detailInfo: {
    padding: '0',
    color: '#000',
  },
  detailTitle: {
    fontSize: '32px',
    fontWeight: '800',
    marginBottom: '15px',
    color: '#000',
    textTransform: 'uppercase',
  },
  detailMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginBottom: '20px',
  },
  metaItem: {
    border: '1px solid #000',
    color: '#000',
    padding: '6px 12px',
    fontSize: '13px',
    fontWeight: '600',
  },
  description: {
    fontSize: '15px',
    lineHeight: '1.6',
    color: '#333',
    marginBottom: '25px',
  },
  infoRow: {
    display: 'flex',
    gap: '10px',
    marginBottom: '12px',
    fontSize: '14px',
  },
  infoLabel: {
    color: '#666',
    minWidth: '100px',
    fontWeight: '600',
  },
  infoValue: {
    color: '#000',
    fontWeight: '500',
  },
  adminContainer: {
    padding: '40px 20px',
    color: '#000',
  },
  adminHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
    paddingBottom: '15px',
    borderBottom: '3px solid #000',
  },
  adminTitle: {
    fontSize: '28px',
    fontWeight: '800',
    color: '#000',
    textTransform: 'uppercase',
  },
  addButton: {
    background: '#000',
    color: '#fff',
    border: '2px solid #000',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    textTransform: 'uppercase',
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalContent: {
    background: '#fff',
    padding: '30px',
    width: '100%',
    maxWidth: '500px',
    maxHeight: '90vh',
    overflowY: 'auto',
    border: '3px solid #000',
    color: '#000',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: '800',
    marginBottom: '25px',
    textAlign: 'center',
    color: '#000',
    textTransform: 'uppercase',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#000',
    textTransform: 'uppercase',
  },
  input: {
    padding: '10px 12px',
    border: '2px solid #000',
    background: '#fff',
    color: '#000',
    fontSize: '14px',
    outline: 'none',
    transition: 'all 0.2s',
  },
  inputFocus: {
    boxShadow: '0 0 0 3px rgba(0, 0, 0, 0.05)',
    borderColor: '#000',
  },
  textarea: {
    padding: '10px 12px',
    border: '2px solid #000',
    background: '#fff',
    color: '#000',
    fontSize: '14px',
    outline: 'none',
    minHeight: '100px',
    resize: 'vertical',
    transition: 'all 0.2s',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  buttonGroup: {
    display: 'flex',
    gap: '12px',
    marginTop: '10px',
  },
  submitButton: {
    flex: 1,
    background: '#000',
    color: '#fff',
    border: '2px solid #000',
    padding: '12px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'all 0.2s',
  },
  submitButtonHover: {
    background: '#333',
    transform: 'scale(0.99)',
  },
  cancelButton: {
    flex: 1,
    background: '#fff',
    color: '#000',
    border: '2px solid #000',
    padding: '12px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
  adminTable: {
    width: '100%',
    borderCollapse: 'collapse',
    background: '#fff',
    border: '2px solid #000',
  },
  tableHeader: {
    background: '#000',
  },
  th: {
    padding: '12px 15px',
    textAlign: 'left',
    fontWeight: '700',
    fontSize: '12px',
    color: '#fff',
    textTransform: 'uppercase',
  },
  td: {
    padding: '12px 15px',
    borderBottom: '1px solid #eee',
    fontSize: '13px',
    color: '#000',
  },
  tableImage: {
    width: '50px',
    height: '70px',
    objectFit: 'cover',
    border: '2px solid #000',
  },
  actionButton: {
    padding: '6px 12px',
    border: '2px solid #000',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: '700',
    marginRight: '8px',
    textTransform: 'uppercase',
  },
  editButton: {
    background: '#fff',
    color: '#000',
  },
  deleteButton: {
    background: '#000',
    color: '#fff',
  },
  fileInput: {
    padding: '8px',
    border: '2px dashed #000',
    background: '#fff',
    color: '#000',
    cursor: 'pointer',
    fontSize: '12px',
  },
  previewImage: {
    width: '100%',
    maxHeight: '150px',
    objectFit: 'cover',
    border: '2px solid #000',
    marginTop: '10px',
  },
  backButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    color: '#000',
    textDecoration: 'none',
    fontSize: '14px',
    marginBottom: '20px',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  recommendSection: {
    marginTop: '50px',
    paddingTop: '30px',
    borderTop: '3px solid #000',
  },
  recommendTitle: {
    fontSize: '22px',
    fontWeight: '800',
    marginBottom: '20px',
    color: '#000',
    textTransform: 'uppercase',
  },
  reviewSection: {
    marginTop: '50px',
    paddingTop: '30px',
    borderTop: '3px solid #000',
  },
  reviewList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    marginTop: '20px',
  },
  reviewCard: {
    border: '2px solid #000',
    padding: '20px',
    background: '#fff',
    transition: 'all 0.2s',
  },
  reviewCardHover: {
    borderColor: '#333',
    background: '#fafafa',
  },
  reviewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  reviewUsername: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#000',
    textTransform: 'uppercase',
  },
  reviewDate: {
    fontSize: '12px',
    color: '#666',
    fontWeight: '600',
    opacity: 0.7,
  },
  reviewComment: {
    fontSize: '14px',
    color: '#000',
    lineHeight: '1.7',
    whiteSpace: 'pre-wrap',
  },
  reviewLoginMessage: {
    marginTop: '20px',
    padding: '14px 16px',
    border: '2px solid #000',
    color: '#000',
    fontSize: '13px',
    fontWeight: '700',
    textTransform: 'uppercase',
    background: '#fff',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    color: '#000',
    border: '2px dashed #000',
  },
  emptyIcon: {
    fontSize: '48px',
    marginBottom: '15px',
  },
};
